Add new color mode(s)
alessioC42/lanis-mobile pull request #103
Opened 2024-01-09 18:47 UTC by kurwjan

Jetzt gibt es zwei Optionen, nämlich **Standart** _(mit Lanis-Dunkel-Türkis als Farbe, villt. lassen wir das einfach bei lila)_ und **Dynamisch** _(Auch bekannt als Material You)_.

Man könnte noch mehr Optionen hinzufügen, zB. das vorherige (Material-)Lila oder man immer die jeweilige Farbe der Applets benutzen, aber ich glaube das laggt zu sehr.

- [ ] Add dynamic color support
- [ ] Add preview?

2024-01-09 18:48 UTC, kurwjan commented
Lanis-Dunkel-Türkis:
![image](https://github.com/alessioC42/lanis-mobile/assets/73837560/52d51b41-8156-4b9d-a3a9-70735cd7b77b)

2024-01-10 22:21 UTC, alessioC42 requested changes
_getSchoolTheme wird bei jedem client login ausgeführt. Es sollte, jedoch nur bei einer Erstanmeldung geschehen. Weil sich das nicht ändert macht es mehr sinn, das zur speichern.

Sobald ich die Einstellungen laden will kommt die Fehlermeldung:
[error_theme.txt](https://github.com/alessioC42/lanis-mobile/files/13895120/error_theme.txt)

2024-01-10 23:48 UTC, kurwjan commented
Das zu speichern ist ne gute Idee. Das mit den Fehler passiert, da das Gerät nicht Material You unterstützt und ich habe den Check, ob das existiert, für die Preview nicht eingebaut.

2024-01-11 03:38 UTC, kurwjan commented
![image](https://github.com/alessioC42/lanis-mobile/assets/73837560/f87bb12e-0807-4fc6-86d7-efcad513d327)

2024-01-11 03:40 UTC, kurwjan commented
![image](https://github.com/alessioC42/lanis-mobile/assets/73837560/45153768-fd48-4fe9-a25d-8e6db8046731)

2024-01-11 11:25 UTC, alessioC42 approved these changes

2024-01-11 11:26 UTC, merged