Modify substitutions widget to enable overflow title
alessioC42/lanis-mobile pull request #137
Opened 2024-01-21 21:03 UTC by alessioC42

Hier wird das Substitutionswidget so angepasst, dass es mit längeren Titeln wie in #136 zurechtkommt. Dazu werden Scroller verwendet. 
Jetzt sind auch die Hinweise in der gleichen Zeile wie das Icon.

Bei der Einführung der Laufschrift wurde eine schöne Animation erstellt, die ich beibehalten würde:

https://github.com/alessioC42/lanis-mobile/assets/84250128/075ea33a-ed86-4424-8447-1e502ec86b7f

closes #136

2024-01-21 22:01 UTC, CodeSpoof commented
Wenn man von woanders zu den Vertretungen navigiert, kann man ganz kurz sehen, dass der Titel noch von links reinwandert, auch wenn er sich nicht bewegen soll, weil er kurz genug ist. Kann das ohne allzu viel Aufwand gefixt werden?

2024-01-21 22:06 UTC, CodeSpoof approved these changes
Ich hätte vllt. noch geguckt, dass die Animation, die du meinst nur einmal gespielt wird und nicht bei jedem Wechseln von Tab, sonst alles klar

2024-01-22 16:18 UTC, kurwjan requested changes
![image](https://github.com/alessioC42/lanis-mobile/assets/73837560/ffd1b366-5568-4918-a106-0a1bed1ba429)
Sehr interessant
Werde das später mehr untersuchen

Ich liebe meine Schule

2024-01-22 16:50 UTC, kurwjan commented
```dart
title: Padding(
        padding: const EdgeInsets.only(top: 2),
        child: (substitutionData['Art'] != null) ?
        MarqueeWidget(
          direction: Axis.horizontal,
          child: Text(
            substitutionData['Art'],
            style: Theme.of(context).textTheme.titleLarge,
          ),
        ) : null,
      ),
```

Meine Schule hat ja nicht das SEHR SINNVOLLE Feld "Art".

2024-01-22 16:54 UTC, alessioC42 commented
> Meine Schule hat ja nicht das SEHR SINNVOLLE Feld "Art".

Umso interessanter:
![image](https://github.com/alessioC42/lanis-mobile/assets/84250128/1ecdee8f-d09e-4459-bc9e-8fa22f7403df)
xD

2024-01-22 18:57 UTC, kurwjan approved these changes
geil

2024-01-22 19:53 UTC, CodeSpoof approved these changes

2024-01-22 19:54 UTC, merged