Reguläre Ausdrücke optimieren
alessioC42/lanis-mobile pull request #139
Opened 2024-01-22 17:57 UTC by CodeSpoof

Einige reguläre Ausdrücke sind nicht optimal formuliert oder es wird RegExp verwendet, an Stellen, an denen es nicht notwendig ist.

2024-01-22 18:58 UTC, kurwjan submitted a review, later dismissed

2024-01-22 19:12 UTC, alessioC42 requested changes
Die änderung in Cryptor breakt bei mir Mein Unterricht

2024-01-22 20:13 UTC, CodeSpoof commented
Eigentlich tun beide Ausdrücke das selbe, aber ich finde den Fehler grade nicht

2024-01-23 19:57 UTC, alessioC42 approved these changes

2024-01-24 08:12 UTC, kurwjan approved these changes

2024-01-24 18:42 UTC, merged