Exceptions statt Status-Codes
alessioC42/lanis-mobile pull request #155
Opened 2024-01-31 19:35 UTC by CodeSpoof

Schnellere Ausführung und statisches typing (Close #154)

2024-01-31 20:24 UTC, CodeSpoof commented
Vorerst nur für client.login() verwendet zum Testen. Zu große Änderungen auf einmal sind zu aufwendig zu mergen. Issue bleibt daher offen. Mache ich aber in kleinen Schritten weiter.

2024-02-01 07:38 UTC, kurwjan commented
Wenn ihr alle den Code aufräumt, sollte ich villt. auch mal den Login aufräumen. Er ist schlimm

2024-02-01 13:23 UTC, alessioC42 requested changes
![image](https://github.com/alessioC42/lanis-mobile/assets/84250128/a2bf506d-e606-4595-8f6f-c0074ec3d0d2)
Zeigt beim login den falschen text an

2024-02-02 10:12 UTC, alessioC42 approved these changes

2024-02-03 21:51 UTC, kurwjan approved these changes

2024-02-03 21:52 UTC, merged