Login rework
alessioC42/lanis-mobile pull request #169
Opened 2024-02-05 11:17 UTC by kurwjan

- [ ] Rework
- [ ] Benutzerdefinierter Lademodus
  - [ ] Update-Interval einstellen?

2024-02-05 17:35 UTC, kurwjan commented
Der Login an sich ist fertig, jedoch könnte man home_page.dart und villt. main.dart bissl refactoren.

2024-02-12 12:59 UTC, kurwjan commented
Jetzt ist das fertig und man muss nur noch den Merge Conflict beheben.

Eigentlich ist das noch ein Dorn im Auge, aber das kann man mal später ändern:
```dart
enum Feature {
  substitutions("Vertretungsplan"),
  calendar("Kalender"),
  conversations("Nachrichten"),
  lessons("Mein Unterricht"),
  lanisBrowser(null),
  moodleBrowser(null),
  settings(null),
  reportBug("Fehlerbericht senden");

  const Feature(this.title);

  final String? title;
}
```

2024-02-12 14:19 UTC, alessioC42 requested changes
Willkommen in meinem Pain. Das letzte Mal, als ich die BottomNavBar gemacht habe, habe ich mindestens 2 Stunden damit verbracht, sicherzustellen, dass die richtigen Indexe aufgerufen werden. Das ist jetzt nicht mehr der Fall. Statt "Mein Unterricht" wird "Nachrichten" geladen, was offensichtlich zu einem Fehler führt. 

Auch die Einträge im NavigationDrawer sind nach dem Gleichen Prinzip nicht mehr korrekt, wenn ein Applet nicht mehr unterstützt wird.

2024-02-12 14:27 UTC, alessioC42 requested changes

2024-02-12 14:27 UTC, alessioC42 commented on app/lib/view/settings/subsettings/start_apps.dart
Als Benutzer verstehe ich nicht, was ich hier einstellen kann. Auch die Grammatik stimmt nicht.

2024-02-12 15:49 UTC, kurwjan commented
> Willkommen in meinem Pain. Das letzte Mal, als ich die BottomNavBar gemacht habe, habe ich mindestens 2 Stunden damit verbracht, sicherzustellen, dass die richtigen Indexe aufgerufen werden. Das ist jetzt nicht mehr der Fall. Statt "Mein Unterricht" wird "Nachrichten" geladen, was offensichtlich zu einem Fehler führt.
> 
> Auch die Einträge im NavigationDrawer sind nach dem Gleichen Prinzip nicht mehr korrekt, wenn ein Applet nicht mehr unterstützt wird.

Ich hoffe das funktioniert jetzt

2024-02-12 15:50 UTC, kurwjan commented on app/lib/view/settings/subsettings/start_apps.dart
Mein Deutschunterricht mit DeepL beginnt wieder

2024-02-12 16:03 UTC, CodeSpoof approved these changes
Es gab im Debugger zwar noch einen Fehler, wenn man bereits angemeldet war und der Banner-Hintergrund daher nicht runtergeladen war, aber der Fehler war nur im Debugger und nicht in der App zu sehen.

2024-02-12 16:19 UTC, kurwjan commented on app/lib/view/settings/subsettings/start_apps.dart
Ich hoffe der jetztige Text ist besser

2024-02-12 16:21 UTC, kurwjan commented
> Es gab im Debugger zwar noch einen Fehler, wenn man bereits angemeldet war und der Banner-Hintergrund daher nicht runtergeladen war, aber der Fehler war nur im Debugger und nicht in der App zu sehen.

Im Release-Build, wenn man bereits angemeldet war, wird der Banner heruntergeladen?

2024-02-13 10:41 UTC, alessioC42 requested changes
![image](https://github.com/alessioC42/lanis-mobile/assets/84250128/ce3223bb-49bf-4866-ae67-4b29776e83ec)
Die Bottomnavbar funktioniert, aber der Navigationdrawer nicht. 

Teste, indem du doesSupportFeature auf false setzt.

2024-02-15 12:57 UTC, alessioC42 commented
Ich übernehme. Das geht wieder nicht.

2024-02-15 18:51 UTC, alessioC42 commented
@kurwjan Kannst du noch docstings zu den neuen API's, die du gemacht hast hinzufügen?

2024-02-15 19:46 UTC, kurwjan commented
> @kurwjan Kannst du noch docstings zu den neuen API's, die du gemacht hast hinzufügen?

Habs gemacht.
Hab auch wieder `NavigationDestinationLabelBehavior.onlyShowSelected` zur bottomNav hinzugefügt sonst sieht es zu voll aus.

2024-02-15 19:54 UTC, alessioC42 approved these changes
Ich möchte mich in naher Zukunft auch mit Bildanimationen beschäftigen. Vielleicht kann man so eine Art Übergang vom Logo des Schulportals zum Logo der App machen. Zumindest sieht das in meinem Kopf gerade toll aus xD

2024-02-15 20:01 UTC, kurwjan commented
> Ich möchte mich in naher Zukunft auch mit Bildanimationen beschäftigen. Vielleicht kann man so eine Art Übergang vom Logo des Schulportals zum Logo der App machen. Zumindest sieht das in meinem Kopf gerade toll aus xD

Das wäre schon super, sowas würde ich villt. auch machen wenn ich jemals mit #40 `Animation` anfangen würde.

2024-02-17 17:29 UTC, CodeSpoof approved these changes

2024-02-17 17:52 UTC, merged