Added Proxy Support
alessioC42/lanis-mobile pull request #231
Opened 2024-06-19 12:37 UTC by Rajala1404

By using the http_proxy Package i was able to implement Proxy Support. Also works with Auto Config

2024-06-19 12:50 UTC, alessioC42 requested changes
That's a bummer, I didn't think to override the global instance, only the separate dio instance. xD

Still have to test it, but looks good as of now.

2024-06-19 12:50 UTC, alessioC42 commented on app/lib/main.dart
> +    WidgetsFlutterBinding.ensureInitialized();
This line can be removed. It was already called on line 29

2024-06-19 13:37 UTC, Rajala1404 commented
Before you merge I need to Revert my Commit (Theme) that wasn't meant for this Pull Request.

2024-06-19 17:50 UTC, Rajala1404 commented
Is now ready to merge

2024-06-20 15:47 UTC, alessioC42 approved these changes
Looks good. The only problem I see is that `http_proxy` uses deprecated API's, but that should be fixable with a PR on this project.
 I think I will look into it. Might be a small step to learn java

2024-06-20 15:47 UTC, merged