Amoled Theme (Pure Black Theme)
alessioC42/lanis-mobile pull request #237
Opened 2024-07-03 19:51 UTC by Rajala1404

I think it would be pretty nice to Implement an Amoled Theme (Pure Black Background) because on AMOLED displays pure black looks really good (at least in my opinion). I already have a implementation for this Feature that still Supports Material You Color Theming (except for the Background of course). Some People argue that Pure Black is bad because it makes for them it more difficult to read the Text but that shouldn't be a Problem because the Small Text are in there Chips that are Themed by Material You. My Implementation is still not Final because the App needs to be restart if you switch to AMOLED or back from AMOLED but that can be fixed by a Popup that Gives a Button to Restart or something like that. After I'm done i would open a Pull Request. Here are some Pictures of my Implementation, just need Feedback if that would be good: 
![combined1](https://github.com/alessioC42/lanis-mobile/assets/115874847/15fd5075-f277-43ee-bc4c-4dcf47fab0aa)
![combined2](https://github.com/alessioC42/lanis-mobile/assets/115874847/8e01923a-e4c3-45bc-be05-f2260d050693)
![combined3](https://github.com/alessioC42/lanis-mobile/assets/115874847/7dae4387-b934-46cf-ba7c-37c9e1e3bce7)
The Background of Timetable Popup is not Pure Black that just looks like that on the Screenshot or maybe its just my Crappy TV Screen

2024-07-07 02:46 UTC, Rajala1404 commented
Feature implementation is done. Switching to Amoled and away from Amoled needs an Restart from the App (doesn't work if Dart Compiler is attached, App closes then but works in Flawless without Dart Compiler attached) switching between Light, Dark, System still happens dynamically (so no restart needed)
![combined](https://github.com/alessioC42/lanis-mobile/assets/115874847/cf512a91-a89d-42db-93dc-18ff1b53524b)

2024-07-07 09:23 UTC, alessioC42 reviewed
I cannot get my head around why a restart is required at all when there should only be a change in the theme. Could you explain why it is required?

2024-07-07 09:23 UTC, alessioC42 commented on app/lib/themes.dart
> +      if (globalStorage.prefs.getString("theme") == "amoled") {
We do not use magic strings to use the globalStorage class. Have a look at storage.dart and other calls of globalStorage

2024-07-07 09:29 UTC, alessioC42 requested changes
Also, the code contains a lot of "special cases" for amoled (which leads to unreadability), mostly due to the restart implementation.

2024-07-07 11:55 UTC, Rajala1404 commented
> I cannot get my head around why a restart is required at all when there should only be a change in the theme. Could you explain why it is required?

The Restart is required because i can't find a way to reload the ThemeData or just change the needed Values outside of ThemeData and if the App doesn't get restarted an it attemps Dynamic switching it causes unintended behavior. If you dynamicly change from Dark to Amoled, nothing happens, or if you dynamicly change from Amoled to Light, it looks really wierd

2024-07-07 12:21 UTC, alessioC42 commented
https://stackoverflow.com/questions/49164592/flutter-how-to-change-the-materialapp-theme-at-runtime
This approach should be modifiable to work. Introducing enums or a custom data class for themes with accent color or something and using the streambuilder to update it. Even the current DynamicColorBuilder should be integratable. 

I defently won't merge the "restart" approach due to its unnatural UX design element.

2024-07-07 12:36 UTC, Rajala1404 commented
> https://stackoverflow.com/questions/49164592/flutter-how-to-change-the-materialapp-theme-at-runtime
>
Yeah that looks good i try this approach

2024-07-08 20:44 UTC, kurwjan commented
Couldn't you just add "amoled" to the `ThemeModeNotifier`? I'll test it.

2024-07-08 21:00 UTC, kurwjan commented
``` dart
return ValueListenableBuilder<Themes>(
          valueListenable: ColorModeNotifier.notifier,
          builder: (_, theme, __) {
            return ValueListenableBuilder<ThemeMode>(
                valueListenable: ThemeModeNotifier.notifier,
                builder: (_, mode, __) {
                  return MaterialApp(
                    title: 'Lanis Mobile',
                    theme: theme.lightTheme,
                    darkTheme: theme.darkTheme,
                    themeMode: mode,
                    localizationsDelegates:
                        AppLocalizations.localizationsDelegates,
                    supportedLocales: AppLocalizations.supportedLocales,
                    home: const StartupScreen(),
                  );
                });
          });
```

You could check here if a ValueNotifier Amoled is true with ValueListenableBuilder, make a function which takes the current dark theme (`theme.darkTheme`) and return it with `theme.darkTheme.copyWith(your modification....)` in `themes.dart`.

2024-07-10 12:11 UTC, Rajala1404 commented
@kurwjan You're approach sounds good but if i try to implement it its the same problem as before that it doesn't get changed until a reload (maybe i just misintepreterted your idea if so just say it) i tried it like this:
```dart
amoled(Themes theme) {
      // Colors for Amoled Mode
      final Map<String, Color> amoledColors = {
        "background": Colors.black,
        "secondary": const Color(0xFF0f0f0f),
        "third": const Color(0xFF0a0a0a),
      };
      String? currentTheme = globalStorage.prefs.getString("theme");

      if (currentTheme == "amoled") {
        return theme.darkTheme?.copyWith(
          // Amoled Background & Themes for required Components
            scaffoldBackgroundColor: amoledColors["background"],
            navigationBarTheme: NavigationBarThemeData(
              backgroundColor: amoledColors["background"],
            ),
            ...other modifications
        );
      } else {
        return theme.darkTheme;
      }
    }

      ...

      return ValueListenableBuilder<Themes>(
          valueListenable: ColorModeNotifier.notifier,
          builder: (_, theme, __) {
            return ValueListenableBuilder<ThemeMode>(
                valueListenable: ThemeModeNotifier.notifier,
                builder: (_, mode, __) {
                  return MaterialApp(
                    title: 'Lanis Mobile',
                    theme: theme.lightTheme,
                    darkTheme: amoled(theme),
                    themeMode: mode,
                    localizationsDelegates:
                    AppLocalizations.localizationsDelegates,
                    supportedLocales: AppLocalizations.supportedLocales,
                    home: const StartupScreen(),
                  );
                });
          });
    });
```

2024-07-13 22:18 UTC, kurwjan commented
I added a new ValueListenableBuilder with a ValueNotifier (`AmoledNotifier`) packed in class with other useful  like the other notifiers and also changed the Amoled radio button to a checkbox (i didn't said that bc i came up with this idea later).

But code still needs to be cleaned up and translation.

2024-07-13 22:58 UTC, Rajala1404 commented
Thanks @kurwjan for the implementation, i cleaned up all my commented code (that needed the Restart) and translation is already present from my previous commits so i think it's ready for a merge. Tested with my S23+ (Android 14) and looks beautiful.

2024-07-13 23:07 UTC, Rajala1404 commented
Ok after some further testing i noticed that the Amoled theme was not preserved after a restart (the checkbox was preserved (checked)) maybe it doesn't get properly loaded at startup it starts working again after unchecking and rechecking the box

2024-07-13 23:27 UTC, Rajala1404 commented
Fixed that amoled mode was not preserved after restart. 
At 123 instead of calling `String isAmoled = await globalStorage.read(key: StorageKey.settingsIsAmoled);` for the isAmoled setting it called `String theme =await globalStorage.read(key: StorageKey.settingsSelectedTheme);` which caused it to return `dark` instead of true/false

2024-07-14 08:20 UTC, alessioC42 approved these changes
Looks fine for me. @kurwjan any thoughts?

2024-07-14 12:51 UTC, kurwjan approved these changes
super

2024-07-14 13:49 UTC, merged