Conversations improvement
alessioC42/lanis-mobile pull request #89
Opened 2023-12-23 01:13 UTC by kurwjan

_Teil von bessere UI/UX (#40 )_

- [ ] Kleinere Änderungen wie Padding oder so.
- [ ] Markdown support

2023-12-23 18:52 UTC, kurwjan commented
Für die Zukunft wenn man das wieder braucht:

```dart
String convertLanisSyntax(String lanisStyledText) {
    final markdown = Markdown.map(
      {
        "**": (text, match) => "<bold>$text</bold>",
        "__": (text, match) => "<underline>$text</underline>",
        "~~": (text, match) => "<italic>$text</italic>",
        "--": (text, match) => "<remove>$text</remove>",
        r"regexp: - .(.*)": (text, match) => "<bullet>$text</bullet>", //wird schon gemacht
        "`": (text, match) => "<code>$text</code>",
        r"regexp: _(\d) ": (text, match) => "<superscript>$text</superscript>",
        r"regexp: _\((\d*)\)": (text, match) => "<superscript>$text</superscript>",
        r"regexp: \^(\d) ": (text, match) => "<subscript>$text</subscript>",
        r"regexp: \^\((\d*)\)": (text, match) => "<subscript>$text</subscript>",
      }
    );

    print(markdown.apply(lanisStyledText));

    return markdown.apply(lanisStyledText);
  }
```

2023-12-26 16:37 UTC, kurwjan commented
Das sollte eigentlich easy sein mit StyledText. Für links und so weiß ich nicht wie ich es genau mache, aber ich glaube mit Linkify suche ich links und emails heraus und tuhe sie in einen tag rein.

2023-12-27 13:34 UTC, kurwjan commented
Vorher:
![Screenshot from 2023-12-27 14-33-41](https://github.com/alessioC42/lanis-mobile/assets/73837560/92c21dd7-f85e-40dc-89c2-75eaf516bfa5)

Nacher:
![Screenshot from 2023-12-27 14-34-27](https://github.com/alessioC42/lanis-mobile/assets/73837560/8632f6cb-ce22-4f5e-abc8-1d0b8b2134e7)

2023-12-27 13:35 UTC, alessioC42 commented
sieht sick aus!

2023-12-27 17:27 UTC, alessioC42 requested changes
Ich kann es nicht wirklich testen...
Aber da das Text-Styling nicht nur in Conversations verwendet wird, wäre es meiner Meinung nach besser, ein eigenes Widget in Shared zu machen. So könnte man es leichter wiederverwenden. Vor allem für eventuelle zukünftige Applets und Mein Unterricht.

2023-12-27 22:25 UTC, kurwjan commented
Hab gemacht

2023-12-27 22:42 UTC, alessioC42 approved these changes

2023-12-27 22:42 UTC, merged